use std::{
    env,
    error::Error,
    fs, io,
    path::{Path, PathBuf},
};

use lightningcss::stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet};
use minify_js::{Session, TopLevelMode, minify};
use sha2::{Digest, Sha256};

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=migrations");
    println!("cargo::rerun-if-changed=src/dashboard");

    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is missing")?;
    let output = env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?;
    let root = Path::new(&manifest);
    let output = Path::new(&output);
    let dashboard = root.join("src/dashboard");

    // Components keep their styles and scripts beside the Rust that renders them.
    let mut css_files = Vec::new();
    let mut js_files = Vec::new();
    collect_assets(&dashboard, &mut css_files, &mut js_files)?;
    let base_styles = dashboard.join("styles.css");
    css_files
        .sort_by(|left, right| (left != &base_styles, left).cmp(&(right != &base_styles, right)));
    js_files.sort();

    let css = concatenate_assets(&css_files, "\n")?;
    let mut stylesheet = StyleSheet::parse(
        &css,
        ParserOptions {
            filename: "src/dashboard (combined CSS)".into(),
            ..ParserOptions::default()
        },
    )
    .map_err(|error| io::Error::other(format!("parse CSS: {error}")))?;
    stylesheet
        .minify(MinifyOptions::default())
        .map_err(|error| io::Error::other(format!("minify CSS: {error}")))?;
    let css = stylesheet
        .to_css(PrinterOptions {
            minify: true,
            ..PrinterOptions::default()
        })?
        .code;

    // Newlines end trailing line comments; semicolons separate standalone scripts.
    let javascript = concatenate_assets(&js_files, "\n;\n")?;
    let session = Session::new();
    let mut js = Vec::new();
    // The page loads a classic deferred script, so preserve global-script semantics.
    minify(
        &session,
        TopLevelMode::Global,
        javascript.as_bytes(),
        &mut js,
    )
    .map_err(|error| io::Error::other(format!("minify src/dashboard JavaScript: {error:?}")))?;

    let css_url = write_asset(output, "css", css.as_bytes())?;
    let js_url = write_asset(output, "js", &js)?;
    fs::write(
        output.join("assets.rs"),
        format!(
            r#"// Generated by build.rs; edit styles and scripts in src/dashboard/ instead.
pub const CSS_URL: &str = {css_url:?};
pub const JS_URL: &str = {js_url:?};
pub const CSS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/site.css"));
pub const JS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/site.js"));
"#
        ),
    )?;
    Ok(())
}

fn collect_assets(
    directory: &Path,
    css: &mut Vec<PathBuf>,
    javascript: &mut Vec<PathBuf>,
) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let path = entry.path();
        if file_type.is_dir() {
            collect_assets(&path, css, javascript)?;
        } else if file_type.is_file() {
            match path.extension().and_then(|extension| extension.to_str()) {
                Some("css") => css.push(path),
                Some("js") => javascript.push(path),
                _ => {}
            }
        }
    }
    Ok(())
}

fn concatenate_assets(files: &[PathBuf], separator: &str) -> io::Result<String> {
    let mut combined = String::new();
    for path in files {
        let source = fs::read_to_string(path).map_err(|error| {
            io::Error::new(error.kind(), format!("read {}: {error}", path.display()))
        })?;
        combined.push_str(&source);
        combined.push_str(separator);
    }
    Ok(combined)
}

fn write_asset(output: &Path, extension: &str, bytes: &[u8]) -> io::Result<String> {
    // Only Cargo's output directory contains generated files. The binary embeds them.
    fs::write(output.join(format!("site.{extension}")), bytes)?;
    let digest = Sha256::digest(bytes);
    Ok(format!("/assets/site.{digest:x}.{extension}"))
}
